### ISSUE TITLE
Move all TODO items from source to issues

### ISSUE THREAD

**Issue by marcpage** [marcpage/libernet#3]
There are several TODO or @todo tags in the source. These should be moved to github issues.

**Comment by marcpage** [comment]
All TODO and @todo in AddressHistory have been added as issues

**Comment by marcpage** [comment]
- [ ] Bundle.h:22:        @todo Document
- [ ] Bundle.h:78:  /// @todo Test
- [ ] Bundle.h:82:  /// @todo Test
- [ ] Bundle.h:105:  // TODO: Make flush and reset virtual and override them here to clear cache
- [ ] Bundle.h:166:/// @todo Test
- [ ] Bundle.h:183:/// @todo Test
- [ ] Bundle.h:324:/// @todo Test
- [ ] Bundle.h:376:/// @todo Test
- [ ] Bundle.h:409:/// @todo Test
- [ ] Bundle.h:461:      // TODO Validate the timestamps are sequential
- [ ] Data.h:56:// TODO: Validate identifiers and keys are hashes
- [ ] Identity.h:12:/// @todo Document
- [ ] JSONData.h:9:/// @todo document
- [ ] JSONData.h:10:/// @todo cache json, move _changeContent here, changes get pushed then
- [ ] Karma.h:9:/// @todo document
- [ ] Karma.h:24:  /// @todo test
- [ ] LargeFile.h:15:// TODO: clean up all files to use auto
- [ ] OwnerIdentity.h:12:/// @todo Document
- [ ] PersonalInformation.h:94:/// @todo Test
- [ ] PersonalInformation.h:139:/// @todo Test
- [ ] PersonalInformation.h:174:/// @todo Test
- [ ] Trust.h:8:/// @todo document
- [ ] Trust.h:9:/// @todo add comments to Trust document for identities (also update readme)
